-- require("core.plugin_config.material")
require("core.plugin_config.lualine")
-- require("core.plugin_config.nvim-tree")
require("core.plugin_config.neo-tree")
require("core.plugin_config.indent")
-- require("core.plugin_config.vscode")
-- require("core.plugin_config.gruvbox")
require("core.plugin_config.farout")
require("core.plugin_config.indentscope")
require("core.plugin_config.treesitter")
require("core.plugin_config.bufferline")
require("core.plugin_config.noice_cmd_line")
--require("core.plugin_config.vim-surround")
